apiVersion: v1
kind: Service

metadata:
  name: devops-ai-service
  namespace: ai-platform

spec:
  selector:
    app: devops-ai-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: NodePort