replicaCount: 2

image:
  repository: devops-ai-platform
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"

  limits:
    memory: "256Mi"
    cpu: "250m"